// generated by scripts/devbok.mjs - do not edit by hand (rebuild: node scripts/devbok.mjs index)
window.DEVBOK_TOPICS = [
  {
    "slug": "angular",
    "title": "Angular",
    "topic": "Angular",
    "accent": "#dd0031",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/angular/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/angular/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/angular/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/angular/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "csharp",
    "title": "C#",
    "topic": "C#",
    "accent": "#512bd4",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/csharp/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/csharp/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/csharp/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/csharp/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "csharp-async",
    "title": "C# async/await",
    "topic": "C# async/await and the Task-based asynchronous pattern (Task, ValueTask, cancellation, IAsyncEnumerable, ConfigureAwait, thread-pool behaviour; assume general C# syntax is known)",
    "accent": "#512bd4",
    "created": "2026-09-07",
    "kinds": {
      "study": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/csharp-async/study.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "0b4185bd",
          "file": "topics/csharp-async/study.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "6b29eaac",
          "file": "topics/csharp-async/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/csharp-async/experience.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "7074fd8c",
          "file": "topics/csharp-async/experience.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "891dff1c",
          "file": "topics/csharp-async/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/csharp-async/interview.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "c299b6a0",
          "file": "topics/csharp-async/interview.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "6fbc2cc4",
          "file": "topics/csharp-async/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/csharp-async/cheatsheet.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "c8cf7b15",
          "file": "topics/csharp-async/cheatsheet.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "436d8839",
          "file": "topics/csharp-async/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "system-design",
    "title": "System design (.NET full-stack)",
    "topic": "System design (as a full-stack .NET engineer, incl. JS FE, databases, and everything inbetween)",
    "accent": "#0e7c86",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/system-design/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/system-design/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/system-design/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/system-design/cheatsheet.v1.html"
        }
      ]
    }
  }
];
