// generated by scripts/devbok.mjs - do not edit by hand (rebuild: node scripts/devbok.mjs index)
window.DEVBOK_CATEGORIES = [
  {
    "id": "language",
    "label": "Languages"
  },
  {
    "id": "backend",
    "label": "Backend & APIs"
  },
  {
    "id": "frontend",
    "label": "Frontend"
  },
  {
    "id": "data",
    "label": "Data & storage"
  },
  {
    "id": "architecture",
    "label": "Architecture & design"
  },
  {
    "id": "ops",
    "label": "Cloud & DevOps"
  },
  {
    "id": "ai",
    "label": "AI engineering"
  },
  {
    "id": "practice",
    "label": "Practices"
  },
  {
    "id": "other",
    "label": "Other"
  }
];
window.DEVBOK_TOPICS = [
  {
    "slug": "angular",
    "title": "Angular",
    "topic": "Angular",
    "category": "frontend",
    "accent": "#dd0031",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/angular/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/angular/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/angular/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/angular/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "appsec",
    "title": "Application security",
    "topic": "Application security",
    "category": "practice",
    "accent": "#1d4ed8",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "3e395ac4",
          "file": "topics/appsec/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "f284a113",
          "file": "topics/appsec/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "880c04f3",
          "file": "topics/appsec/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/appsec/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "aspnet",
    "title": "ASP.NET Core & .NET runtime",
    "topic": "ASP.NET Core & .NET runtime (assume C# language features are already covered; focus on the framework and runtime)",
    "category": "backend",
    "accent": "#512bd4",
    "created": "2026-09-08",
    "kinds": {
      "study": [],
      "experience": [],
      "interview": [],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/aspnet/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "azure",
    "title": "Azure cloud",
    "topic": "Azure cloud",
    "category": "ops",
    "accent": "#0078d4",
    "created": "2026-09-08",
    "kinds": {
      "study": [],
      "experience": [],
      "interview": [],
      "cheatsheet": []
    }
  },
  {
    "slug": "csharp",
    "title": "C#",
    "topic": "C#",
    "category": "language",
    "accent": "#512bd4",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/csharp/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/csharp/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/csharp/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/csharp/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "csharp-async",
    "title": "C# async/await",
    "topic": "C# async/await and the Task-based asynchronous pattern (Task, ValueTask, cancellation, IAsyncEnumerable, ConfigureAwait, thread-pool behaviour; assume general C# syntax is known)",
    "category": "language",
    "accent": "#512bd4",
    "created": "2026-09-07",
    "kinds": {
      "study": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/csharp-async/study.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "0b4185bd",
          "file": "topics/csharp-async/study.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "6b29eaac",
          "file": "topics/csharp-async/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/csharp-async/experience.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "7074fd8c",
          "file": "topics/csharp-async/experience.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "891dff1c",
          "file": "topics/csharp-async/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/csharp-async/interview.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "c299b6a0",
          "file": "topics/csharp-async/interview.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "6fbc2cc4",
          "file": "topics/csharp-async/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 3,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/csharp-async/cheatsheet.v3.html"
        },
        {
          "v": 2,
          "generated": "2026-09-08",
          "prompt": "c8cf7b15",
          "file": "topics/csharp-async/cheatsheet.v2.html"
        },
        {
          "v": 1,
          "generated": "2026-09-07",
          "prompt": "436d8839",
          "file": "topics/csharp-async/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "distributed",
    "title": "Distributed systems & messaging",
    "topic": "Distributed systems & messaging",
    "category": "architecture",
    "accent": "#c2410c",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "3e395ac4",
          "file": "topics/distributed/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "f284a113",
          "file": "topics/distributed/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "880c04f3",
          "file": "topics/distributed/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/distributed/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "jsts",
    "title": "JavaScript & TypeScript",
    "topic": "JavaScript and TypeScript",
    "category": "language",
    "accent": "#3178c6",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "3e395ac4",
          "file": "topics/jsts/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "f284a113",
          "file": "topics/jsts/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "880c04f3",
          "file": "topics/jsts/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/jsts/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "modernization",
    "title": "Modernization (.NET full-stack)",
    "topic": "Software Modernization for .NET+JS/TS+Database+Azure full-stack engineers",
    "category": "architecture",
    "accent": "#c2410c",
    "created": "2026-09-08",
    "kinds": {
      "study": [],
      "experience": [],
      "interview": [],
      "cheatsheet": []
    }
  },
  {
    "slug": "observability",
    "title": "Observability & prod debugging",
    "topic": "Observability & production debugging",
    "category": "ops",
    "accent": "#f5a800",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "3e395ac4",
          "file": "topics/observability/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "f284a113",
          "file": "topics/observability/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "880c04f3",
          "file": "topics/observability/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/observability/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "react",
    "title": "React",
    "topic": "React",
    "category": "frontend",
    "accent": "#087ea4",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "3e395ac4",
          "file": "topics/react/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "f284a113",
          "file": "topics/react/experience.v1.html"
        }
      ],
      "interview": [],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/react/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "sql",
    "title": "SQL (SQL Server & PostgreSQL)",
    "topic": "SQL Server and PostgreSQL (if they differ, mention both separately)",
    "category": "data",
    "accent": "#336791",
    "created": "2026-09-08",
    "kinds": {
      "study": [],
      "experience": [],
      "interview": [],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "ccd2d4a9",
          "file": "topics/sql/cheatsheet.v1.html"
        }
      ]
    }
  },
  {
    "slug": "system-design",
    "title": "System design (.NET full-stack)",
    "topic": "System design (as a full-stack .NET engineer, incl. JS FE, databases, and everything inbetween)",
    "category": "architecture",
    "accent": "#0e7c86",
    "created": "2026-09-08",
    "kinds": {
      "study": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "475abea6",
          "file": "topics/system-design/study.v1.html"
        }
      ],
      "experience": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "4ab84a97",
          "file": "topics/system-design/experience.v1.html"
        }
      ],
      "interview": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "c7153c25",
          "file": "topics/system-design/interview.v1.html"
        }
      ],
      "cheatsheet": [
        {
          "v": 1,
          "generated": "2026-09-08",
          "prompt": "eef70255",
          "file": "topics/system-design/cheatsheet.v1.html"
        }
      ]
    }
  }
];
